spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yroom
    username: root
    password: root
    
mybatis:
  mapper-locations:
    /mappers/*.xml